
[theme]
primaryColor = "#4CAF50"
backgroundColor = "#262730"
secondaryBackgroundColor = "#1A1A1A"
textColor = "#FFFFFF"
font = "sans serif"
base = "dark"

#[ui]
#hideSidebarNav = true       # ✅ 페이지 목록 숨기기